version: "3.2"

services:
  mysql:
    image: mysql:5.7.23
    container_name: mysql
    hostname: mysql
    env_file:
      - ./mysql.env
    restart: always

  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
